### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [Smooth-E/wireless-adb-switch#10]
First congrats to your listing at F-Droid! At this point, apps are usually removed from my repo (to make room for other apps; my repo runs on limited personal space). I see my badge is still present here, so how shall we proceed?

**Comment by Smooth-E** [comment]
Hello! Since F-Droid is generally more popular and your repository is an addition to it, I think we can proceed with the removal of WADBS from your repository.

I would like to thank you for sparkling my interest in developing this project further as I saw more and more people using the app (as they star this repository) after you offered to publish it on IzzyOnDroid!

I will now remove the IzzyOnDroid badge, so you can delete the listing.

**Comment by IzzySoft** [comment]
Thanks @Smooth-E – and glad I was able to give you a boost :smiley: Will remove the app then at my end as agreed. Should you need it back for some reason one day, just give me a ping.
