### ISSUE TITLE
help

### ISSUE THREAD

**Issue by thimonnguyen1996** [Smooth-E/wireless-adb-switch#12]
![Screenshot_20240111-170444_WADBS](https://github.com/Smooth-E/wireless-adb-switch/assets/85774909/974f5fa0-8193-491a-95eb-f042b769e745)

**Comment by Smooth-E** [comment]
What is the problem exactly?

**Comment by Smooth-E** [comment]
This issue seems to be stale. In case you didn't solve your problem by now, refer to the readme and its sections (scripts and other ones). For advanced integrations to work you need KDE Connect installed (either form Google Play. F-Droid or from somewhere else). You also need root access or Shizuku (enabled from the PC, this is important) for WADBS to work.

Closing this issue as resolved for now. Feel free to reopen it if you still need help.
