### ISSUE TITLE
[question] Can we `adb connect` in termux?

### ISSUE THREAD

**Issue by Freed-Wu** [Smooth-E/wireless-adb-switch#16]
I try to start WADBS by shizuku. In another machine I try to `adb connect` and succeed. However, In android machine which run WADBS, I try to `adb connect` in termun, It return:

```
failed to connect to IP:port
```

Can we `adb connect` in termux?

TIA!

**Comment by Smooth-E** [comment]
Not sure, honestly. But why would you like to `adb connect` to the same device? Also, there are apps on the F-Droid (and, probably, Google Play) that allow you to do this.

**Comment by Freed-Wu** [comment]
> why would you like to

Oh, I just want to `adb connect` to the same device, then use `adb shell` in termux to do something like `adb install /the/path.apk` to simplify some things.

I found [`rish`](https://github.com/RikkaApps/Shizuku-API/tree/master/rish) can do some work such as:

- `rish -c 'pm install XXX.apk'`, `adb install XXX.apk`
- `rish`, `adb shell`
- ...

Although rish can do some work about adb, I still want to know the answer of this question. Some user who prefer `adb` and some prefer `rish`, I think both are OK.

**Comment by Smooth-E** [comment]
I actually forgot about `rish` when writing my previous message. I did integrate Shizuku into WADBS, but personally I do not use it since all my devices are rooted for development purposes.

So, `rish` is meant to provide you the privilege level of ADB without extra hassle. While you can install `android-tools` in Termux and use ADB directly, `rish` is still more convenient especially if you set up Shizuku for some other app anyway. As far as I understand, you can think of `rish` as executing a command inside `adb shell`, so it can do not *some*, but all of the work that `adb shell` can.

On the point of connecting through wireless ADB. What `IP:PORT` configuration are you using? The loopback address is `127.0.0.1` or `localhost`. You may want to try these.

Either way, WADBS does not focus on providing ADB functionality. You will get more answers if you ask on a specific subreddit like [r/AndroidRoot](https://www.reddit.com/r/androidroot/) or on a forum like XDA.
