### ISSUE TITLE
[BUG] widget says disconnected, when it is indeed connected.

Android 14
Samsung S23 Ultra
OneUI 6.1
mode: Shizuku
app downloaded from github

### ISSUE THREAD

**Issue by drewauff** [Smooth-E/wireless-adb-switch#22]
# System information

> Describe your setup, so we can understand the cause of the bug better

- Android version: <e.g. Android 12>
- Android vendor: <e.g. MIUI, OneUI, Lineage OS>
- Mode: <root or Shizuku>
- WADBS version: <e.g. 1.0>
- Where did you get the app from: <e.g. IzzyOnDroid or GitHub Releases page>
- Any additional information you would like to share about your system

# Problem description

> Describe your problem with as much detail as possible. 
> You may want to include some specific conditions the problem is occurring because of in your opinion (e.g. the widget is not working, but you are using a custom home screen launcher).
> Provide error logs if you are able to get any. You can capture logs using your PC or an app such as MatLog on your Android device.

- [ ] This issue was not reported before
- [ ] I agree to keep the discussion polite and on point

**Comment by Smooth-E** [comment]
Hello!

First of all, it seems like I really have to improve the issue template, because a lot of people are misusing it.

Now regarding your issue. You mentioned that you are using Shizuku mode. Did you [start Shizuku from your computer](https://shizuku.rikka.app/guide/setup/#start-by-connecting-to-a-computer)? Otherwise, if you [used wireless debugging to enable it](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging), Shizuku won't work for WADBS. Refer to [this](https://github.com/Smooth-E/wireless-adb-switch/issues/2#issuecomment-1817233501) comment for more info.

**Comment by drewauff** [comment]
Samsung S23 Ultra
Android 14 (stock)
unrooted
Shizuku
WADBS 1.1
Github
---------------------

I start Shizuku locally on my phone

I also have a Tasker profile to (more or less) keep  wireless debugging active and thererfore Shizuku.

**Comment by Smooth-E** [comment]
> I start Shizuku locally on my phone

To properly use WADBS, you will have to [start Shizuku from your PC](https://shizuku.rikka.app/guide/setup/#start-by-connecting-to-a-computer). If you are using [this method](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging), it won't work.

> I also have a Tasker profile to (more or less) keep wireless debugging active

What do you mean by this?

To clarify. The purpose of WADBS is to provide a quick way of turning wireless debugging on and off, with some convenience features like KDE Connect integration. WADBS is not an alternative to wireless debugging, it is just a tool that utilizes (hidden) system functionality.

**Comment by drewauff** [comment]
to start Shizuku you have to 

1) Turn on wifi
2)  activate wireless debugging and then
3) run the Shizuku startup script

normally to run the script you would have to launch the Shizuku app the tap start.

I use Tasker to automate all of the that...

I want to use WADBS to sho the current IP and port on my desktop as a widget.

But as it stands right now the widget just display disconnected. Sometimes  it does work but not for long.

**Comment by Smooth-E** [comment]
Can you describe in more detail, what your Tasker script does? Does the issue occur when you disable wireless debugging and then enable it back or does it occur completely randomly?

**Comment by drewauff** [comment]
This is the script that turns on wifi debugging if it is not already on

  ` A1: Custom Setting [
         Type: Global
         Name: adb_wifi_enabled
         Value: 1
         Continue Task After Error:On ]`

This is the script that check to see wireless debugging if it is running/activated then run the Shizuku startup script if
wifi debugging is not active then activate it and then run the Shizuku starup script.

` A1: Tasker Function [
         Function: CheckADBWifi() ]
    
    A2: If [ %has_adb_wifi !~ true ]
    
        A3: Flash [
             Text: No access to ADB WiFi
             Continue Task Immediately: On
             Dismiss On Click: On ]
    
        A4: Stop [ ]
    
    A5: End If
    
    A6: ADB Wifi [
         Command: sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh
         Timeout (Seconds): 1 ]`

**Comment by Smooth-E** [comment]
During development I did not encounter such issue. The fact that wireless debugging turns off automatically when you disconnect from wifi (or if the network goes out of reach, for example) may be relevant. Also keep in mind that widgets update on an interval of about 2-3 seconds (even though the slider goes down to one second).

**Comment by Smooth-E** [comment]
Okay, I guess I stumbled upon the same problem as you did. For me sometimes the connection details widget says there is no connection even though there is. This varies from device to device. Since I am using the command line API or a hidden API, I generally cannot expect it to be stable. Since I usually have my widget update interval set to one second, the widget displays correct information on the next update. I will definitely look into this problem later, but for now it's a wont-fix. Feel free to reopen if you find a good path to consistently replicate this or if you determine the external conditions for this to occur. Thanks for being interesting in WADBS!

**Comment by drewauff** [comment]
appreciate the effort..Thank you 👍🏼
