### ISSUE TITLE
Switch to activate Shizuku

### ISSUE THREAD

**Issue by Terkyz** [Smooth-E/wireless-adb-switch#3]
I know this and Shizuku are two separate apps and maybe I should rather request this on the Shizuku Github, but it would be great to be able to activate Shizuku in one click from a switch just like you activate or deactivate the debugger mode.

**Comment by Smooth-E** [comment]
I don't really get what you are requesting. 

Shizuku requires [some extra setup](https://shizuku.rikka.app/guide/setup/#start-shizuku) to be activated, and I don't really know the way to deactivate it completely (apart from rebooting or withdrawing the root access permission). You can manage which apps are allowed to use Shizuku from the *"Authorized applications* tab.

As I mentioned [here](https://github.com/Smooth-E/wireless-adb-switch/issues/2#issuecomment-1769257361), next release of WADBS will include support for Shizuku as an alternative to root access and will be available soon.

**Comment by Terkyz** [comment]
You are right, I did not describe the issue well.

What I wanted to say is, to make use of WADBS I have two options: I create a WADBS widget in the home of my launcher and when I press it I activate the debugger mode. Or I can also press the WADBS button in the buttons that appear when I slide down the notifications of my device (I don't remember how that menu is called).

My request is not a button to do an automatic setup of Shizuku, because I know that involves many steps, including pairing. I was referring to a new widget or button in the notifications menu that when pressed will perform the same function as opening Shizuku (already configured by the user) and pressing the "Start" button.

**Comment by Smooth-E** [comment]
Well, as you have said, such switch is out of scope for WADBS. This feature is better to be implemented on Shizuku's side.

Interacting with a different app (from a widget, let's say), requires that app to have an interface for such interaction. This interface must be open for other apps to access, or otherwise it will require root access. This is actually why KDE Connect integration won't work without root, because it has to pass an intent to a not-exported activity (see [this](https://github.com/Smooth-E/wireless-adb-switch/blob/50acfd2d2a03939a0043f73c460a080848194be8/app/src/main/java/com/smoothie/wirelessDebuggingSwitch/KdeConnect.kt#L30C9-L30C9) if you are interested).

Thank you for the feature request! I am closing the issue as not planned now.
